
import { UserRole, TaskStatus } from './types';

export const TRANSLATIONS = {
  pt: {
    brandName: 'GESTORA',
    dashboard: 'Painel Principal',
    opportunities: 'Oportunidades',
    contracts: 'Contratos',
    clients: 'Clientes',
    articles: 'Artigos',
    events: 'Actividades',
    tasks: 'Gestão de Tarefas',
    invoicing: 'Faturação',
    nonConformities: 'Conformidades',
    users: 'Gestão de Usuários',
    profile: 'Perfil',
    logout: 'Sair',
    createTask: 'Nova Tarefa',
    editTask: 'Editar',
    deleteTask: 'Excluir',
    search: 'Procurar por título...',
    filterByStatus: 'Filtrar por Estado',
    allStatuses: 'Todos os Estados',
    noTasks: 'Nenhum registro encontrado.',
    responsible: 'Responsável Principal',
    intervenientes: 'Intervenientes',
    startDate: 'Data de Início',
    deadline: 'Prazo',
    deliveryDate: 'Entrega Prevista',
    days: 'Dias',
    hours: 'Horas',
    description: 'Descrição Detalhada',
    title: 'Título da Tarefa',
    status: 'Estado Atual',
    updateStatus: 'Avançar Status',
    closeTask: 'Validar e Fechar',
    latestUpdates: 'Actividade Recente',
    notifications: 'Notificações',
    overdue: 'Atrasada',
    extendDeadline: 'Prorrogar Prazo',
    save: 'Salvar',
    cancel: 'Cancelar',
    login: 'Acesso ao Sistema',
    email: 'Endereço de E-mail',
    password: 'Palavra-passe',
    landingTitle: 'A gestão de atividades da sua equipe levada ao próximo nível de excelência',
    landingDesc: 'Simplifique processos, monitore prazos com precisão cirúrgica e impulsione a performance do seu time com a ferramenta de gestão mais intuitiva do mercado.',
    accessSystem: 'Entrar no Sistema',
    back: 'Voltar',
    welcome: 'Olá,',
    activeTasks: 'Ativas',
    overdueTasks: 'Em Atraso',
    completedTasks: 'Concluídas',
    addUser: 'Adicionar Usuário',
    manageUsers: 'Gestão de Equipe',
    settings: 'Configurações',
    theme: 'Tema',
    language: 'Idioma',
    startNow: 'Comece Agora',
    startFree: 'Teste Gratuitamente',
    learnMore: 'Saiba Mais',
    // New translations for expanded features
    name: 'Nome',
    position: 'Cargo',
    department: 'Departamento',
    editUser: 'Editar Usuário',
    deleteUser: 'Deletar Usuário',
    activateUser: 'Ativar Usuário',
    deactivateUser: 'Desativar Usuário',
    userProfile: 'Perfil do Usuário',
    editProfile: 'Editar Perfil',
    changeAvatar: 'Alterar Foto',
    myProfile: 'Meu Perfil',
    darkMode: 'Modo Escuro',
    lightMode: 'Modo Claro',
    portuguese: 'Português',
    english: 'Inglês',
    reports: 'Relatórios Gerenciais',
    taskMetrics: 'Métricas de Tarefas',
    userPerformance: 'Desempenho da Equipe',
    productivityReport: 'Relatório de Produtividade',
    totalTasks: 'Total de Tarefas',
    activeCount: 'Tarefas Ativas',
    completedCount: 'Tarefas Concluídas',
    overdueCount: 'Tarefas Atrasadas',
    completionRate: 'Taxa de Conclusão',
    averageDelay: 'Atraso Médio',
    taskDistribution: 'Distribuição de Tarefas',
    validateTask: 'Validar Tarefa',
    reopenTask: 'Reabrir Tarefa',
    taskDetails: 'Detalhes da Tarefa',
    extendDate: 'Estender Prazo',
    extendDays: 'Dias para Estender',
    sendForValidation: 'Enviar para Validação',
    validationFeedback: 'Feedback de Validação',
    validatedBy: 'Validado por',
    validatedAt: 'Validado em',
    recentActivity: 'Actividade Recente',
    taskCreated: 'Tarefa criada com sucesso',
    taskUpdated: 'Tarefa atualizada',
    taskDeleted: 'Tarefa deletada',
    statusChanged: 'Status alterado para',
    taskValidated: 'Tarefa validada',
    deadlineApproaching: 'Prazo se aproximando',
    taskOverdue: 'Tarefa atrasada',
    delayCausesMoreDelay: 'Seu atraso nos atrasa',
    taskCompleted: 'Você finalizou a tarefa com sucesso',
    hasTaskToStart: 'Você tem uma tarefa por fazer',
    noNotifications: 'Tudo em dia',
    viewMore: 'Ver mais',
    markAsRead: 'Marcar como lido',
    clearAll: 'Limpar tudo',
    noUsers: 'Nenhum usuário encontrado',
    selectUser: 'Selecione um usuário',
    areYouSure: 'Tem certeza?',
    userAdded: 'Usuário adicionado com sucesso',
    userUpdated: 'Usuário atualizado',
    userDeleted: 'Usuário deletado',
    close: 'Fechar',
    edit: 'Editar',
    delete: 'Deletar',
    confirm: 'Confirmar',
    loading: 'Carregando...',
    errorOccurred: 'Erro ao processar requisição',
    success: 'Sucesso',
    warning: 'Aviso',
    error: 'Erro',
    info: 'Informação',
    responsibles: 'Responsáveis',
    roadmap: 'Roadmap',
    enterprise: 'Enterprise',
    features: 'Funcionalidades'
  },
  en: {
    brandName: 'GESTORA',
    dashboard: 'Dashboard',
    opportunities: 'Opportunities',
    contracts: 'Contracts',
    clients: 'Clients',
    articles: 'Articles',
    events: 'Activities',
    tasks: 'Task Management',
    invoicing: 'Invoicing',
    nonConformities: 'Conformities',
    users: 'Users',
    profile: 'Profile',
    logout: 'Logout',
    createTask: 'New Task',
    editTask: 'Edit',
    deleteTask: 'Delete',
    search: 'Search by title...',
    filterByStatus: 'Filter Status',
    allStatuses: 'All Statuses',
    noTasks: 'No tasks found.',
    responsible: 'Main Responsible',
    intervenientes: 'Stakeholders',
    startDate: 'Start Date',
    deadline: 'Deadline',
    deliveryDate: 'Estimated Delivery',
    days: 'Days',
    hours: 'Hours',
    description: 'Detailed Description',
    title: 'Task Title',
    status: 'Current Status',
    updateStatus: 'Advance Status',
    closeTask: 'Validate & Close',
    latestUpdates: 'Recent Activity',
    notifications: 'Notifications',
    overdue: 'Overdue',
    extendDeadline: 'Extend Deadline',
    save: 'Save',
    cancel: 'Cancel',
    login: 'System Login',
    email: 'Email Address',
    password: 'Password',
    landingTitle: 'Your team activity management taken to the next level of excellence',
    landingDesc: 'Simplify processes, monitor deadlines with surgical precision and boost your team performance with the most intuitive management tool on the market.',
    accessSystem: 'Sign In',
    back: 'Back',
    welcome: 'Hello,',
    activeTasks: 'Active',
    overdueTasks: 'Overdue',
    completedTasks: 'Completed',
    addUser: 'Add User',
    manageUsers: 'Team Management',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    startNow: 'Start Now',
    startFree: 'Start Free',
    learnMore: 'Learn More',
    // New translations for expanded features
    name: 'Name',
    position: 'Position',
    department: 'Department',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    activateUser: 'Activate User',
    deactivateUser: 'Deactivate User',
    userProfile: 'User Profile',
    editProfile: 'Edit Profile',
    changeAvatar: 'Change Avatar',
    myProfile: 'My Profile',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    portuguese: 'Portuguese',
    english: 'English',
    reports: 'Management Reports',
    taskMetrics: 'Task Metrics',
    userPerformance: 'Team Performance',
    productivityReport: 'Productivity Report',
    totalTasks: 'Total Tasks',
    activeCount: 'Active Tasks',
    completedCount: 'Completed Tasks',
    overdueCount: 'Overdue Tasks',
    completionRate: 'Completion Rate',
    averageDelay: 'Average Delay',
    taskDistribution: 'Task Distribution',
    validateTask: 'Validate Task',
    reopenTask: 'Reopen Task',
    taskDetails: 'Task Details',
    extendDate: 'Extend Deadline',
    extendDays: 'Days to Extend',
    sendForValidation: 'Send for Validation',
    validationFeedback: 'Validation Feedback',
    validatedBy: 'Validated By',
    validatedAt: 'Validated At',
    recentActivity: 'Recent Activity',
    taskCreated: 'Task created successfully',
    taskUpdated: 'Task updated',
    taskDeleted: 'Task deleted',
    statusChanged: 'Status changed to',
    taskValidated: 'Task validated',
    deadlineApproaching: 'Deadline approaching',
    taskOverdue: 'Task is overdue',
    delayCausesMoreDelay: 'Your delay delays us',
    taskCompleted: 'You completed the task successfully',
    hasTaskToStart: 'You have a task to start',
    noNotifications: 'All caught up',
    viewMore: 'View More',
    markAsRead: 'Mark as Read',
    clearAll: 'Clear All',
    noUsers: 'No users found',
    selectUser: 'Select a user',
    areYouSure: 'Are you sure?',
    userAdded: 'User added successfully',
    userUpdated: 'User updated',
    userDeleted: 'User deleted',
    close: 'Close',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',
    errorOccurred: 'Error processing request',
    success: 'Success',
    warning: 'Warning',
    error: 'Error',
    info: 'Information',
    responsibles: 'Assignees',
    roadmap: 'Roadmap',
    enterprise: 'Enterprise',
    features: 'Features'
  }
};

export const MOCK_USERS: any[] = [
  { id: 'u-admin', name: 'Luciano Alfredo', email: 'admin@gestora.com', password: '123', role: UserRole.ADMIN, position: 'Diretor Geral', department: 'Diretoria' },
  { id: 'u-emp1', name: 'João Silva', email: 'joao@gestora.com', password: '123', role: UserRole.EMPLOYEE, position: 'Analista Sênior', department: 'TI' },
  { id: 'u-emp2', name: 'Ana Costa', email: 'ana@gestora.com', password: '123', role: UserRole.EMPLOYEE, position: 'Coordenadora de Projetos', department: 'Operações' },
  { id: 'u-user', name: 'Usuário Padrão', email: 'usuario@gestora.com', password: '123', role: UserRole.EMPLOYEE, position: 'Operador', department: 'Geral' }
];

export const INITIAL_TASKS: any[] = [
  {
    id: 'T-001',
    title: 'Análise de Fluxo Operacional',
    description: 'Avaliação detalhada dos processos de entrega do departamento comercial.',
    startDate: '2024-03-20T09:00:00.000Z',
    deadlineValue: 5,
    deadlineType: 'days',
    deliveryDate: '2026-03-25T09:00:00.000Z',
    responsibleId: 'u-emp1',
    intervenientes: ['u-emp2'],
    status: TaskStatus.ABERTO,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'T-002',
    title: 'Manutenção Preventiva de TI',
    description: 'Checkup geral nos servidores de contingência e sistemas de segurança.',
    startDate: '2024-03-21T10:00:00.000Z',
    deadlineValue: 24,
    deadlineType: 'hours',
    deliveryDate: '2026-03-22T10:00:00.000Z',
    responsibleId: 'u-emp1',
    intervenientes: ['u-emp2'],
    status: TaskStatus.POR_INICIAR,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'T-003',
    title: 'Desenvolvimento do Módulo de Relatórios',
    description: 'Implementação do sistema de geração de relatórios gerenciais com gráficos e exportação.',
    startDate: '2024-03-18T08:00:00.000Z',
    deadlineValue: 10,
    deadlineType: 'days',
    deliveryDate: '2026-03-28T08:00:00.000Z',
    responsibleId: 'u-emp1',
    intervenientes: ['u-emp2', 'u-admin'],
    status: TaskStatus.EM_PROGRESSO,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'T-004',
    title: 'Revisão de Documentação Técnica',
    description: 'Atualização completa da documentação técnica do sistema para a nova versão.',
    startDate: '2024-03-15T09:00:00.000Z',
    deadlineValue: 7,
    deadlineType: 'days',
    deliveryDate: '2026-03-22T09:00:00.000Z',
    responsibleId: 'u-emp2',
    intervenientes: ['u-emp1'],
    status: TaskStatus.TERMINADO,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'T-005',
    title: 'Auditoria de Segurança',
    description: 'Análise completa de vulnerabilidades e implementação de correções de segurança.',
    startDate: '2024-03-10T10:00:00.000Z',
    deadlineValue: 14,
    deadlineType: 'days',
    deliveryDate: '2024-03-24T10:00:00.000Z',
    responsibleId: 'u-emp2',
    intervenientes: ['u-emp1', 'u-admin'],
    status: TaskStatus.FECHADO,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    closedAt: new Date().toISOString()
  },
  {
    id: 'T-006',
    title: 'Integração com Sistema Externo',
    description: 'Desenvolvimento da API de integração com o sistema de gestão financeira.',
    startDate: '2024-03-01T08:00:00.000Z',
    deadlineValue: 5,
    deadlineType: 'days',
    deliveryDate: '2024-03-06T08:00:00.000Z',
    responsibleId: 'u-emp1',
    intervenientes: ['u-emp2'],
    status: TaskStatus.ATRASADA,
    comments: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const STATUS_COLORS: Record<TaskStatus, string> = {
  [TaskStatus.ABERTO]: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400',
  [TaskStatus.POR_INICIAR]: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
  [TaskStatus.EM_PROGRESSO]: 'bg-blue-600 text-white',
  [TaskStatus.TERMINADO]: 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400',
  [TaskStatus.FECHADO]: 'bg-slate-900 text-white dark:bg-slate-700',
  [TaskStatus.ATRASADA]: 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400'
};
